# Generated by Django 3.0.4 on 2021-04-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategory',
            name='SubscriberId',
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='JobCategoryId',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
